import { Client, Vehicle, Mechanic, Part, ServiceOrder, Invoice, User, SystemNotification } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u-admin',
    name: 'Carlos Alberto (Admin)',
    email: 'admin@oficina.com',
    role: 'admin',
    roleLabel: 'Administrador Geral',
    avatarColor: 'bg-red-600',
  },
  {
    id: 'u-atendente',
    name: 'Ana Paula Costa',
    email: 'atendente@oficina.com',
    role: 'atendente',
    roleLabel: 'Recepcionista / Atendente',
    avatarColor: 'bg-blue-600',
  },
  {
    id: 'u-mec-1',
    name: 'Mestre João Silva',
    email: 'joao@oficina.com',
    role: 'mecanico',
    roleLabel: 'Mecânico Chefe (Motor)',
    avatarColor: 'bg-amber-600',
    mechanicId: 'mec-1',
  },
  {
    id: 'u-mec-2',
    name: 'António Langa',
    email: 'antonio@oficina.com',
    role: 'mecanico',
    roleLabel: 'Mecânico Técnico (Eletricidade)',
    avatarColor: 'bg-emerald-600',
    mechanicId: 'mec-2',
  },
];

export const INITIAL_MECHANICS: Mechanic[] = [
  {
    id: 'mec-1',
    name: 'Mestre João Silva',
    specialty: 'Motores e Transmissões',
    phone: '+258 84 123 4567',
    email: 'joao@oficina.com',
    status: 'ativo',
  },
  {
    id: 'mec-2',
    name: 'António Langa',
    specialty: 'Eletricidade e Eletrónica Automóvel',
    phone: '+258 82 987 6543',
    email: 'antonio@oficina.com',
    status: 'ativo',
  },
  {
    id: 'mec-3',
    name: 'Mateus Manhiça',
    specialty: 'Suspensão, Freios e Direção',
    phone: '+258 87 555 1212',
    email: 'mateus@oficina.com',
    status: 'ativo',
  },
  {
    id: 'mec-4',
    name: 'Fernando Macamo',
    specialty: 'Diagnóstico Computadorizado',
    phone: '+258 84 333 4444',
    email: 'fernando@oficina.com',
    status: 'inativo',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Manuel dos Santos',
    phone: '+258 84 500 1122',
    email: 'manuel.santos@email.com',
    address: 'Av. Eduardo Mondlane, nº 1420, Maputo',
    document: '100234589', // NUIT
    createdAt: '2026-01-15',
  },
  {
    id: 'cli-2',
    name: 'Maria Esperança Macuácua',
    phone: '+258 82 344 5566',
    email: 'maria.esperanca@email.com',
    address: 'Bairro da Polana Cimento B, Rua das Acácias, nº 88',
    document: '100876543', // NUIT
    createdAt: '2026-01-20',
  },
  {
    id: 'cli-3',
    name: 'Transportes TransLomaco Lda',
    phone: '+258 87 222 9900',
    email: 'contacto@translomaco.co.mz',
    address: 'Zona Industrial da Matola, Parcela 40',
    document: '400192837', // NUIT Empresa
    createdAt: '2026-02-05',
  },
  {
    id: 'cli-4',
    name: 'Dr. Lucas Nhantumbo',
    phone: '+258 84 777 8899',
    email: 'lucas.nhantumbo@saude.gov.mz',
    address: 'Av. Julius Nyerere, Sommerchield, Maputo',
    document: '100456123',
    createdAt: '2026-02-18',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    clientId: 'cli-1',
    plate: 'AFM-423-MC',
    brand: 'Toyota',
    model: 'Hilux D-4D 3.0',
    year: 2021,
    color: 'Branco Prata',
    mileage: 85400,
    createdAt: '2026-01-15',
  },
  {
    id: 'veh-2',
    clientId: 'cli-2',
    plate: 'ABM-902-MP',
    brand: 'Nissan',
    model: 'Qashqai 1.6 dCi',
    year: 2019,
    color: 'Cinzento Metálico',
    mileage: 62100,
    createdAt: '2026-01-20',
  },
  {
    id: 'veh-3',
    clientId: 'cli-3',
    plate: 'MLT-114-MC',
    brand: 'Isuzu',
    model: 'D-Max 250 Fleetside',
    year: 2022,
    color: 'Branco',
    mileage: 110200,
    createdAt: '2026-02-05',
  },
  {
    id: 'veh-4',
    clientId: 'cli-4',
    plate: 'AGK-330-MP',
    brand: 'Mercedes-Benz',
    model: 'C200 Avantgarde',
    year: 2020,
    color: 'Preto Obsidiana',
    mileage: 49500,
    createdAt: '2026-02-18',
  },
];

export const INITIAL_PARTS: Part[] = [
  {
    id: 'part-1',
    code: 'FIL-OLEO-TY01',
    name: 'Filtro de Óleo Sintético Toyota/Isuzu',
    category: 'Filtros e Fluidos',
    quantity: 18,
    minQuantity: 5,
    unitPrice: 850,
    supplier: 'AutoPeças Moçambique Lda',
  },
  {
    id: 'part-2',
    code: 'OLEO-5W30-SYN',
    name: 'Óleo de Motor Sintético 5W-30 (Galão 5L)',
    category: 'Filtros e Fluidos',
    quantity: 12,
    minQuantity: 4,
    unitPrice: 3200,
    supplier: 'TotalEnergies Moçambique',
  },
  {
    id: 'part-3',
    code: 'PAST-TRAVAO-FR',
    name: 'Jogo de Pastilhas de Travão Dianteiras',
    category: 'Sistema de Travagem',
    quantity: 6,
    minQuantity: 3,
    unitPrice: 2800,
    supplier: 'Brembo Distribuidora',
  },
  {
    id: 'part-4',
    code: 'CORREIA-DENT-02',
    name: 'Kit de Correia de Distribuição c/ Tensor',
    category: 'Motor',
    quantity: 1, // Alerta de estoque baixo!
    minQuantity: 3,
    unitPrice: 7500,
    supplier: 'Continental Automotive',
  },
  {
    id: 'part-5',
    code: 'VELAS-IGN-IRID',
    name: 'Jogo de 4 Velas de Ignição Iridium',
    category: 'Eletricidade e Ignição',
    quantity: 8,
    minQuantity: 2,
    unitPrice: 1950,
    supplier: 'NGK Spark Plugs',
  },
  {
    id: 'part-6',
    code: 'BATERIA-70AH-MF',
    name: 'Bateria Selada 12V 70Ah Livre de Manutenção',
    category: 'Baterias e Elétrica',
    quantity: 4,
    minQuantity: 2,
    unitPrice: 6800,
    supplier: 'Willard Baterias',
  },
  {
    id: 'part-7',
    code: 'AMORT-DIANT-HLX',
    name: 'Amortecedor Dianteiro a Gás Reforçado',
    category: 'Suspensão',
    quantity: 0, // Esgotado!
    minQuantity: 2,
    unitPrice: 5400,
    supplier: 'Monroe Distribuição',
  },
];

export const INITIAL_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: 'OS-2026-001',
    clientId: 'cli-1',
    vehicleId: 'veh-1',
    mechanicId: 'mec-1',
    problemDescription: 'Revisão periódica dos 85.000 km e ruído metálico ao travar em declive.',
    diagnosis: 'Desgaste acentuado das pastilhas de travão dianteiras e necessidade de troca de óleo e filtro.',
    status: 'Concluída',
    createdAt: '2026-03-01 08:30',
    completedAt: '2026-03-02 16:00',
    laborCost: 3500,
    partsUsed: [
      {
        partId: 'part-1',
        partName: 'Filtro de Óleo Sintético Toyota/Isuzu',
        partCode: 'FIL-OLEO-TY01',
        quantity: 1,
        unitPrice: 850,
        total: 850,
      },
      {
        partId: 'part-2',
        partName: 'Óleo de Motor Sintético 5W-30 (Galão 5L)',
        partCode: 'OLEO-5W30-SYN',
        quantity: 1,
        unitPrice: 3200,
        total: 3200,
      },
      {
        partId: 'part-3',
        partName: 'Jogo de Pastilhas de Travão Dianteiras',
        partCode: 'PAST-TRAVAO-FR',
        quantity: 1,
        unitPrice: 2800,
        total: 2800,
      },
    ],
    invoiceId: 'FAT-2026-001',
    notes: 'Cliente satisfeito, teste de estrada aprovado.',
  },
  {
    id: 'OS-2026-002',
    clientId: 'cli-2',
    vehicleId: 'veh-2',
    mechanicId: 'mec-2',
    problemDescription: 'Luz da bateria acesa no painel e dificuldade na partida matinal.',
    diagnosis: 'Alternador com carga irregular e bateria desgastada que não retém carga.',
    status: 'Em execução',
    createdAt: '2026-03-05 09:15',
    laborCost: 2000,
    partsUsed: [
      {
        partId: 'part-6',
        partName: 'Bateria Selada 12V 70Ah Livre de Manutenção',
        partCode: 'BATERIA-70AH-MF',
        quantity: 1,
        unitPrice: 6800,
        total: 6800,
      },
    ],
    notes: 'Aguardando teste final do circuito elétrico do alternador.',
  },
  {
    id: 'OS-2026-003',
    clientId: 'cli-3',
    vehicleId: 'veh-3',
    mechanicId: 'mec-3',
    problemDescription: 'Forte batida na suspensão dianteira esquerda em terreno irregular.',
    diagnosis: 'Amortecedor dianteiro estourado e sem ação. Peça esgotada no stock.',
    status: 'Aguardando peça',
    createdAt: '2026-03-07 10:00',
    laborCost: 2500,
    partsUsed: [],
    notes: 'OS marcada como Aguardando peça: Amortecedor Dianteiro a Gás (Código AMORT-DIANT-HLX) solicitado ao fornecedor.',
  },
  {
    id: 'OS-2026-004',
    clientId: 'cli-4',
    vehicleId: 'veh-4',
    mechanicId: 'mec-1',
    problemDescription: 'Falhas de ignição ao acelerar em subidas e luz de motor piscando.',
    diagnosis: 'Velas com folga excessiva e fuligem.',
    status: 'Pendente',
    createdAt: '2026-03-08 14:20',
    laborCost: 1800,
    partsUsed: [],
    notes: 'Aguardando início da desmontagem e verificação pelo Mecânico João.',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'FAT-2026-001',
    serviceOrderId: 'OS-2026-001',
    clientId: 'cli-1',
    vehicleId: 'veh-1',
    issuedAt: '2026-03-02 16:30',
    partsSubtotal: 6850,
    laborSubtotal: 3500,
    discount: 350,
    discountReason: 'Desconto de cliente fidelidade (5% na mão de obra)',
    taxRate: 16, // IVA 16% em Moçambique
    taxAmount: 1600,
    total: 11600,
    paymentMethod: 'Transferência / M-Pesa',
    status: 'Paga',
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-1',
    title: 'Alerta de Stock Crítico',
    message: 'A peça "Kit de Correia de Distribuição" atingiu o nível mínimo (1 unidade restante).',
    type: 'warning',
    date: '08/03/2026',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'OS Aguardando Peça',
    message: 'Mecânico Mateus marcou a OS-2026-003 como "Aguardando peça" (Amortecedor Dianteiro).',
    type: 'warning',
    date: '07/03/2026',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Fatura Emitida com Sucesso',
    message: 'Fatura FAT-2026-001 liquidada pelo cliente Manuel dos Santos.',
    type: 'success',
    date: '02/03/2026',
    read: true,
  },
];
